### ISSUE TITLE
Add example(s) to repository

### ISSUE THREAD

**Issue by simnh** [znes/renpass#21]
There should be at least one simple exampel that can be run I think

**Comment by ckaldemeyer** [comment]
Thanks for the hint. We already suggested that in the last MoVe. It might be provided through the MENA scenarios by @soenkebohm if there are no licensing issues concerning the data (according to Marina).

Otherwise, we either link the oemof examples or provide an own simple example. Either way, we can and should become more specific and user friendly at different levels.

**Comment by eosram** [comment]
I thought it might also be a good idea to just point to an already published scenario set, downloading it otf when calling main.
